-file("/usr/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(config_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 47).


-define(TOKEN(Type, Line, Value), make_token(Type, Line, Value, Value)).
-define(TOKEN(Type, Line, Value, Text), make_token(Type, Line, Text, Value)).
-define(FORWARD_TOKEN(Line, Text), {token, {list_to_atom(Text), Line}}).
-define(TOKEN_PUSH(Type, Line, Push, Text), {token, {Type, Line, Text}, Push}).


make_token(Type, Line, Text, Fun) when is_function(Fun, 1) ->
    {token, {Type, Line, Fun(Text)}};
    
make_token(Type, Line, _Text, Value) ->
    {token, {Type, Line, Value}}.
    

strip_junk([$\" | Rest]) -> strip_junk(Rest);
strip_junk([$\\ | Rest]) -> strip_junk(Rest);
strip_junk([$\/ | Rest]) -> strip_junk(Rest);
strip_junk(X) -> X.


strip_var([$\$, ${ | Rest]) ->
    lists:reverse( strip_var_end( lists:reverse(Rest) ) );
    
strip_var(X) -> X.


strip_var_end([$} | Rest]) -> Rest;
strip_var_end(X) -> X.


map_escaped_char(Escaped) when is_list(Escaped) ->
    map_escaped_char(hd(Escaped));

map_escaped_char(Escaped) ->
    case Escaped of
        $\\ -> $\\;
        $/  -> $/;
        $\" -> $\";
        $\' -> $\';
        $\( -> $(;
        $b  -> $\b;
        $d  -> $\d;
        $e  -> $\e;
        $f  -> $\f;
        $n  -> $\n;
        $r  -> $\r;
        $s  -> $\s;
        $t  -> $\t;
        $v  -> $\v;
        X   -> X
    end.
  
-file("/usr/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.erl", 337).
yystate() -> 86.

yystate(93, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 51, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(93, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,93};
yystate(92, [46|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 5, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,92};
yystate(91, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line+1, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,91};
yystate(90, [32|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 2, Tlen);
yystate(90, [9|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 2, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,90};
yystate(89, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line+1, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [46|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(84, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,88};
yystate(87, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line+1, Tlen+1, Action, Alen);
yystate(86, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 51, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 101 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 109 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 115 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 120 ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(86, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,86};
yystate(85, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line+1, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, [46|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 5, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, 5, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,84};
yystate(83, [53|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 52 ->
    yystate(47, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 54, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,83};
yystate(82, [13|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 1, Tlen);
yystate(82, [10|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,82};
yystate(81, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(81, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(81, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(81, [C|Ics], Line, Tlen, Action, Alen) when C >= 51, C =< 57 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,81};
yystate(80, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [101|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 8, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,78};
yystate(77, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line+1, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [95|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, [45|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, [46|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, [36|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,76};
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 53 ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,75};
yystate(74, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line+1, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [46|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,72};
yystate(71, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [115|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 8, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,70};
yystate(69, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [45|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [46|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(68, Ics, Line, Tlen+1, 17, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(66, [35|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(66, [10|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line+1, Tlen+1, 15, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 37, C =< 91 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,66};
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(65, Ics, Line, Tlen+1, 6, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,65};
yystate(64, [46|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 53 ->
    yystate(84, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 54, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 3, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(60, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(57, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [53|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 52 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 54, C =< 57 ->
    yystate(84, Ics, Line, Tlen+1, 5, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,55};
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,54};
yystate(53, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line+1, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 14 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [92|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [36|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [35|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [34|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [10|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line+1, Tlen+1, 15, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 37, C =< 91 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(66, Ics, Line, Tlen+1, 15, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,49};
yystate(48, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(48, [69|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(48, [46|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 6, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 6, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,48};
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,47};
yystate(46, [114|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 8, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,46};
yystate(45, [50|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 51, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(43, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(42, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(40, [69|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(40, [46|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 6, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, 6, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,40};
yystate(39, [53|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 52 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 54, C =< 57 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [117|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 8, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(36, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line+1, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 16, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(33, Ics, Line, Tlen+1, 16, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,33};
yystate(32, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 53 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [101|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 8, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,30};
yystate(29, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(28, [69|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 6, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, 6, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,28};
yystate(27, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line+1, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line+1, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [101|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 8, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,25};
yystate(24, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [107|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 8, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,22};
yystate(21, [39|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 13, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 13, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,21};
yystate(20, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(20, [69|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, 6, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(18, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line+1, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [115|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,17};
yystate(16, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line+1, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [111|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 8, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,14};
yystate(13, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(12, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(12, [69|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(12, [46|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 6, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 53 ->
    yystate(28, Ics, Line, Tlen+1, 6, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 54, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, 6, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,12};
yystate(11, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [108|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 8, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,9};
yystate(8, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line+1, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line+1, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,6};
yystate(5, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 64, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(4, [69|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(4, [53|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 6, Tlen);
yystate(4, [46|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 6, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 52 ->
    yystate(48, Ics, Line, Tlen+1, 6, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 54, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 6, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,4};
yystate(3, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [97|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 8, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(54, Ics, Line, Tlen+1, 8, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,1};
yystate(0, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line+1, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, _, _, _) ->
    yyaction_1();
yyaction(2, _, _, _) ->
    yyaction_2();
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 20).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/0}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 21).
yyaction_1() ->
     skip_token .

-compile({inline,yyaction_2/0}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 22).
yyaction_2() ->
     skip_token .

-compile({inline,yyaction_3/1}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 24).
yyaction_3(TokenLine) ->
     ? TOKEN (bool, TokenLine, true) .

-compile({inline,yyaction_4/1}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 25).
yyaction_4(TokenLine) ->
     ? TOKEN (bool, TokenLine, false) .

-compile({inline,yyaction_5/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 27).
yyaction_5(TokenChars, TokenLine) ->
     ? TOKEN (integer, TokenLine, fun erlang : list_to_integer / 1, TokenChars) .

-compile({inline,yyaction_6/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 28).
yyaction_6(TokenChars, TokenLine) ->
     ? TOKEN (float, TokenLine, fun erlang : list_to_float / 1, TokenChars) .

-compile({inline,yyaction_7/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 29).
yyaction_7(TokenChars, TokenLine) ->
     ? TOKEN (ipv4_address, TokenLine, TokenChars) .

-compile({inline,yyaction_8/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 30).
yyaction_8(TokenChars, TokenLine) ->
     ? TOKEN (atom, TokenLine, fun erlang : list_to_atom / 1, TokenChars) .

-compile({inline,yyaction_9/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 31).
yyaction_9(TokenChars, TokenLine) ->
     ? TOKEN (variable, TokenLine, strip_var (TokenChars)) .

-compile({inline,yyaction_10/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 32).
yyaction_10(TokenChars, TokenLine) ->
     ? FORWARD_TOKEN (TokenLine, TokenChars) .

-compile({inline,yyaction_11/1}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 34).
yyaction_11(TokenLine) ->
     ? TOKEN (substring, TokenLine, []) .

-compile({inline,yyaction_12/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 35).
yyaction_12(TokenChars, TokenLine) ->
     ? TOKEN_PUSH (stringvar, TokenLine, "\"", strip_var (strip_junk (TokenChars))) .

-compile({inline,yyaction_13/1}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 36).
yyaction_13(TokenLine) ->
     ? TOKEN_PUSH (substring, TokenLine, "\"", "${") .

-compile({inline,yyaction_14/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 37).
yyaction_14(TokenChars, TokenLine) ->
     ? TOKEN_PUSH (substring, TokenLine, "\"", [map_escaped_char (strip_junk (TokenChars)) ]) .

-compile({inline,yyaction_15/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 38).
yyaction_15(TokenChars, TokenLine) ->
     ? TOKEN_PUSH (substring, TokenLine, "\"", strip_junk (TokenChars)) .

-compile({inline,yyaction_16/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 40).
yyaction_16(TokenChars, TokenLine) ->
     ? TOKEN (anchor, TokenLine, TokenChars) .

-compile({inline,yyaction_17/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 41).
yyaction_17(TokenChars, TokenLine) ->
     ? TOKEN (pathfrag, TokenLine, TokenChars) .

-compile({inline,yyaction_18/2}).
-file("/opt/home/faganm/projects/erlangx/_build/default/lib/systemconf/src/config_lexer.xrl", 42).
yyaction_18(TokenChars, TokenLine) ->
     ? TOKEN (pathvar, TokenLine, strip_var (strip_junk (TokenChars))) .

-file("/usr/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 290).
